CPMAddPackage("gh:catchorg/Catch2@3.7.1")
CPMAddPackage("gh:glfw/glfw#3.4")
# CPMAddPackage("gh:KhronosGroup/Vulkan-Headers@1.4.304")
find_package(Vulkan REQUIRED)
CPMAddPackage("gh:GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator@3.1.0")
CPMAddPackage("gh:g-truc/glm#1.0.1")
